docker-compose:
  image: ${REGISTRY_DOMAIN}/rancher/os-dockercompose:5.1.3
  labels:
    io.rancher.os.scope: system
    io.rancher.os.after: console
    io.docker.compose.rebuild: always
  net: none
  privileged: true
  volumes_from:
  - all-volumes
